version: "3.8"
services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    links:
      - database
    environment:
      - APP_NAME=MyFlaskAPP

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5000:5000"

  database:
    image: mysql:8.0.29
    container_name: database
    ports:
      - "32000:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
