version: "3.8"
services:

  flask:
    build: ./flask
    container_name: music_flask
    restart: always
    environment:
      - APP_NAME=MyFlaskAPP
    expose:
      - 6000
    networks:
      - apps

  nginx:
    build: ./nginx
    container_name: music_nginx
    restart: always
    ports:
      - "5000:5000"
    networks:
      - apps

networks:
  apps:
    external:
      name: apps
