CREATE DATABASE IF NOT EXISTS Music;
USE Music;
CREATE TABLE IF NOT EXISTS Album (
    id VARCHAR(22) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    spotify_url VARCHAR(255) NOT NULL UNIQUE,
    image_url VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS Artist (
    id VARCHAR(22) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    spotify_url VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS Playlist (
    id VARCHAR(22) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    spotify_url VARCHAR(255) NOT NULL UNIQUE,
    image_url VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS Track (
    id VARCHAR(22) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    spotify_url VARCHAR(255) NOT NULL UNIQUE,
    id_album VARCHAR(255) NOT NULL,
    duration_ms MEDIUMINT UNSIGNED NOT NULL,
    FOREIGN KEY (id_album) REFERENCES Album(id)
);
CREATE TABLE IF NOT EXISTS AlbumArtists (
    id_album VARCHAR(22) NOT NULL,
    id_artist VARCHAR(22) NOT NULL,
    FOREIGN KEY (id_album) REFERENCES Album(id),
    FOREIGN KEY (id_artist) REFERENCES Artist(id)
);
CREATE TABLE IF NOT EXISTS TrackArtists (
    id_track VARCHAR(22) NOT NULL,
    id_artist VARCHAR(22) NOT NULL,
    FOREIGN KEY (id_track) REFERENCES Track(id),
    FOREIGN KEY (id_artist) REFERENCES Artist(id)
);
CREATE TABLE IF NOT EXISTS TrackPlaylist (
    id_track VARCHAR(22) NOT NULL,
    id_playlist VARCHAR(22) NOT NULL,
    FOREIGN KEY (id_track) REFERENCES Track(id),
    FOREIGN KEY (id_playlist) REFERENCES Playlist(id)
);