SET GLOBAL connect_timeout=6000;

CREATE DATABASE IF NOT EXISTS Music;
USE Music;

CREATE TABLE IF NOT EXISTS Album (
    id VARCHAR(22) NOT NULL PRIMARY KEY UNIQUE,
    name VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist (
    id VARCHAR(22) NOT NULL PRIMARY KEY UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Playlist (
    id VARCHAR(22) NOT NULL PRIMARY KEY KEY UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Song (
    id VARCHAR(22) NOT NULL PRIMARY KEY KEY UNIQUE,
    name VARCHAR(255) NOT NULL,
    id_album VARCHAR(255) NOT NULL,
    duration_ms MEDIUMINT UNSIGNED NOT NULL,
    FOREIGN KEY (id_album) REFERENCES Album(id)
);

CREATE TABLE IF NOT EXISTS AlbumArtists (
    id_album VARCHAR(22) NOT NULL,
    id_artist VARCHAR(22) NOT NULL,
    FOREIGN KEY (id_album) REFERENCES Album(id),
    FOREIGN KEY (id_artist) REFERENCES Artist(id)
);

CREATE TABLE IF NOT EXISTS SongArtists (
    id_song VARCHAR(22) NOT NULL,
    id_artist VARCHAR(22) NOT NULL,
    FOREIGN KEY (id_song) REFERENCES Song(id),
    FOREIGN KEY (id_artist) REFERENCES Artist(id)
);

CREATE TABLE IF NOT EXISTS SongPlaylist (
    id_song VARCHAR(22) NOT NULL,
    id_playlist VARCHAR(22) NOT NULL,
    FOREIGN KEY (id_song) REFERENCES Song(id),
    FOREIGN KEY (id_playlist) REFERENCES Playlist(id)
);
